Vagrant.configure("2") do |config|
  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "generic/centos9s"
    ansible.vm.box_version = "4.3.12"
    ansible.vm.network "private_network",ip: "192.168.59.108"
    ansible.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
      vb.name = "ansible"
    end
    ansible.vm.provision "shell" , path: "provision.sh"
  end
end
